### ISSUE TITLE
Does it still work for mediatek devices?

### ISSUE THREAD

**Issue by khan7860** [EmperorEye1993/GPU-Turbo-Boost#8]
Hey!
I appreciate the work and I was about to download it, but the description and changelog says it wont support processors other than Snapdragon.
But once going through the already closed issues, 1 of them confirmed that it is supported by Mtk devices.

Still I want to confirm if it would run on Mediatek Helio G90T 

Device name: Redmi Note 8 pro

**Comment by EmperorEye1993** [comment]
As per the previous version some processors are drop to support including MediaTek.

**Comment by Gamemulatorer** [comment]
Dapat pala name ng module na to adreno gpu turbo :/
